### ISSUE TITLE
imageio_ffmpeg We had to kill ffmpeg to stop it, video reader not write!

### ISSUE THREAD

**Issue by mayste** [imageio/imageio-ffmpeg#46]
Hi,
I'm looking for ffmpeg timeout param for video reader.
I need to read a video with resolution 512X512 in batch of 16 frames and do some operations.
How I can increase the timeout for leave the video reader open?
Thanks

**Comment by almarklein** [comment]
Hi @mayste, the API is in the readme - I think you're looking for the `ffmpeg_timeout` parameter.

**Comment by mayste** [comment]
Yes but this parameter is available over writing and not reading

**Comment by almarklein** [comment]
In that case I do not understand the question :) What goes wrong now which you think can be fixed with a timeout?

**Comment by mayste** [comment]
When I’m trying to read a video. I need to leave it open for long time. I got error: We had to kill ffmpeg to stop it.
So I wanted to ask if there is a way to change the timeout or a way to prevent this. 
Thanks

**Comment by almarklein** [comment]
I suspect this is because you read the first few frames and then stop the iteration. The way to tell ffmpeg to stop has changed a couple of times, as different solutions have side effects for certain use-cases. In the current approach we close both stdin and stdout of the ffmpeg subprocess, then wait at most 1.5 s, and then kill it if it has not stopped yet. This was tested to work well, but we appear to have a use-case here for which it does not.

If you could help determine whether this can be improved, that 'd be great. I'd be especially interested if giving ffmpeg more time by increasing the timeout would help. You could try this by increasing the `1.5` here: 

https://github.com/imageio/imageio-ffmpeg/blob/71b2fb0130e92a55d09588e19b5e823566ebb9b4/imageio_ffmpeg/_io.py#L252-L254


I can see a few options:
* Simply increasing the timeout somewhat.
* Making this timeout configurable.
* Disabling the warning message (in theory it's pretty harmless, especially when reading, though I hope we can fix it another way)

**Comment by mayste** [comment]
Thanks, I will try

**Comment by rmahtoa** [comment]
Maybe this can help
https://github.com/ranjeetvit2012/h264-video-conversion-ffmpeg
