### ISSUE TITLE
pkg_resources is deprecated

### ISSUE THREAD

**Issue by nhairs** [imageio/imageio-ffmpeg#98]
When running my own tests the following warning is thrown:
`
  /code/.tox/py311/lib/python3.11/site-packages/imageio_ffmpeg/_utils.py:7: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
`

The fix appears to be to use [`importlib.resources`](https://docs.python.org/3.11/library/importlib.resources.html#module-importlib.resources)

**Comment by almarklein** [comment]
There's a nice migration guide here: https://importlib-resources.readthedocs.io/en/latest/migration.html

I recently made a similar change in another project (https://github.com/pygfx/wgpu-py/pull/421/files). I expect we can do something similar here.

There's no rush, since its only a warning (for now), but if someone is willing to contribute a PR that'd be great 😊

**Comment by almarklein** [comment]
Fixed by #109
